#!/bin/bash
# Test Analytics Events Script
# Run this in the container to test analytics tracking

echo "=========================================="
echo "Analytics Event Testing"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "1. Testing Frontend Event Tracking"
echo "   Open your browser and:"
echo "   - Open DevTools Console (F12)"
echo "   - Run these commands:"
echo ""
echo -e "${YELLOW}// Check if loaded${NC}"
echo "console.log('CKANAnalytics:', typeof window.CKANAnalytics);"
echo "console.log('RudderStack:', typeof rudderanalytics);"
echo ""
echo -e "${YELLOW}// Test search click${NC}"
echo "window.CKANAnalytics.track('Search Result Click-Through', {"
echo "  dataset_title: 'Test',  dataset_url: window.location.href,"
echo "  search_query: 'test', result_position: 1"
echo "});"
echo ""
echo -e "${YELLOW}// Test DOI event${NC}"
echo "window.CKANAnalytics.track('Dataset Published with DOI', {"
echo "  dataset_id: 'test', dataset_title: 'Test',"
echo "  doi_request_timestamp: new Date().toISOString()"
echo "});"
echo ""

echo "2. Check for DOI buttons on dataset page:"
echo "   Run this in browser console on a dataset page:"
echo ""
echo -e "${YELLOW}// Find DOI buttons${NC}"
echo "const selectors = ["
echo "  'a[href*=\"doi/create\"]',"
echo "  'button[name=\"doi\"]',"
echo "  '[data-action=\"create-doi\"]',"
echo "  '.btn-doi-create',"
echo "  'a.btn-doi',"
echo "  'form[action*=\"doi\"] button[type=\"submit\"]'"
echo "];"
echo "selectors.forEach(sel => {"
echo "  const els = document.querySelectorAll(sel);"
echo "  if (els.length) console.log(\`Found: \${sel}\`, els);"
echo "});"
echo ""

echo "3. Check for search result items:"
echo "   Run this on search results page:"
echo ""
echo -e "${YELLOW}// Find dataset items${NC}"
echo "console.log('Items:', document.querySelectorAll('.dataset-item').length);"
echo "console.log('Links:', document.querySelectorAll('.dataset-heading a').length);"
echo ""

echo "4. Check RudderStack Live Events:"
echo "   - Go to: https://app.rudderstack.com/"
echo "   - Navigate to: Your Source → Live Events"
echo "   - Perform actions on your CKAN site"
echo "   - Watch for events appearing in real-time"
echo ""

echo "5. Check browser Network tab:"
echo "   - Open DevTools → Network tab"
echo "   - Filter by: 'rudderstack' or 'track'"
echo "   - Perform actions"
echo "   - Look for POST requests"
echo ""

echo "=========================================="
echo "Common Issues & Solutions"
echo "=========================================="
echo ""
echo "If 'Search Result Click-Through' not firing:"
echo "  - Check browser console for errors"
echo "  - Verify .dataset-item elements exist:"
echo "    document.querySelectorAll('.dataset-item')"
echo "  - Check if event listeners attached"
echo ""
echo "If 'Dataset Published with DOI' not firing:"
echo "  - Find the actual DOI button selector on your page"
echo "  - Look for the button text or class"
echo "  - Add selector to analytics-tracking.js"
echo ""
echo "If no events at all:"
echo "  - Check RUDDERSTACK_ENABLED=true in .env"
echo "  - Rebuild container: docker compose build"
echo "  - Clear browser cache"
echo "  - Check rudderanalytics is loaded"
echo ""
